### ISSUE TITLE
日英のドキュメントはリポジトリを分ける

### ISSUE THREAD

**Issue by tdtds** [tdiary/tdiary-docs-ja#2]
Wikiを触ってみたらディレクトリで構造化はできないようなので、オリジナルのWikiと同様、日本語ドキュメントと英語ドキュメントは別々に管理しないとダメそうです。

なので、

* ここの名称を「tdiary-docs-ja」に変更して日本語ドキュメントを扱う
* 新たに「tdiary-docs-en」を追加して英語ドキュメントを扱う

という変更をしたいと思います。

**Comment by hsbt** [comment]
賛成です!

**Comment by tdtds** [comment]
しました。
