### ISSUE TITLE
Wikiスタイルの「リンク」の説明に誤りがある

### ISSUE THREAD

**Issue by kenichiice** [tdiary/tdiary-docs-ja#5]
[Wikiスタイル](https://github.com/tdiary/tdiary-docs-ja/wiki/Wiki%E3%82%B9%E3%82%BF%E3%82%A4%E3%83%AB) のページにある「リンク」の書式の説明の一部がWikiスタイルではなくmarkdownになってしまっています。

```
[ただのにっき](http://sho.tdiary.net/)
[このファイル](../files/hoge.txt)
[ほげ](hoge:キーワード)
```

[英語版](https://github.com/tdiary/tdiary-docs-en/wiki/WikiStyle) も同様です。

Wikiの編集権限をいただけるようなら私の方で修正することもできるかと思います。

**Comment by tdtds** [comment]
ありがとうございます！ 引っ越しのときの自動変換でよけいなところまで変換しちゃったようですね。権限お渡ししたので、おまかせします。

**Comment by kenichiice** [comment]
日本語版と英語版のWikiスタイルのページを修正しました。

よく読んでみるとリンクの説明以外にもおかしい所が色々あったので、気づいた個所は修正しました。

このissueは閉じておきます。
